[workspace]
resolver = "2"
members = ["crates/chess-lib"]
default-members = ["crates/chess-lib"]

[workspace.dependencies]
# chess-lib = { path = "crates/chess-lib" }
# chess-tui = { path = "crates/chess-tui" }
serde = { version = "1", features = ["derive"] }
# rhai = "1.23.6"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true