[package]
name = "chess-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chess-lib = { workspace = true, features = ["serde"] }

serde = { workspace = true }
serde_json = "1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "std",
    "env-filter",
    "registry",
    'json',
    'tracing-log',
] }

tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls-ring",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
dotenv = "0.15"

actix-web = "4"
actix-multipart = "0.6"
actix-session = { version = "0.7", features = [
    "redis-rs-session",
    "redis-rs-tls-session",
] }

argon2 = "0.5"
pasetors = "0.6"
deadpool-redis = "0.11"
uuid = { version = "1", features = ["v4", "serde"] }
hex = "0.4"

ws = "0.9"
dashmap = "5"
rand = { version = "0.8" }